# See: https://github.com/pr3d4t0r/SSScoring/blob/master/LICENSE.txt

# Use:  streamlit config show to view all options.

[client]
showErrorDetails = 'type'
toolbarMode = 'viewer'

# [global]
# developmentMode=false

[logger]
level = 'critical'

[server]
port = 8080

[theme]
base = 'light'

