#!/usr/bin/env python

# FCC converter:
# https://www.fcc.gov/media/radio/dms-decimal


import pathlib

import pandas as pd


RAW_DATA_FILE = './resources/drop-zones-loc-elev-raw.csv'
RESOURCE_DATA = pathlib.Path('./ssscoring/resources')
RESOURCE_DATA_FILE = RESOURCE_DATA / 'drop-zones-loc-elev.csv'


if '__main__' == __name__:
    # The column names came from Alexey's database, weren't normalized to be
    # Pythonic or dataframe-friendly.  That's OKi.
    rawData = pd.read_csv(RAW_DATA_FILE)
    rawData.DZ = rawData.DZ.fillna(rawData.name)

    data = pd.DataFrame(data = {
        'dropZone': rawData.DZ,
        'lat': rawData.lat,
        'lon': rawData.lon,
        'elevation': rawData.elevation,
        'location': rawData.name,
        'country': rawData.country,
    })
    data.sort_values(by='dropZone', ascending=True, inplace=True)
    data.to_csv(RESOURCE_DATA_FILE, sep=',')
    for item in RESOURCE_DATA.iterdir():
        print('resource file = %s' % item)

