#!/bin/bash 

# vim: set fileencoding=utf-8:
# BSD 3-Clause License -- see LICENSE for details.
# https://github.com/pr3d4t0r/SSScoring for full project.


# *** constants ***

MOUNT_POINT="/Volumes"
OS="Darwin"


# *** functions ***

function die {
    echo "$1"
    exit "$2"
} #die


function assertMacOS {
    [[ $(uname) == "$OS" ]] || die "this tool only works on MacOS" 1
} # assertMacOS


function canonicalPathFor {
    [[ -z "$1" ]] && die "Provide a path to concatenate to $MOUNT_POINT" 3
    echo "$MOUNT_POINT/$1"
} # canonicalPathFor


function assertFlySightDirExists {
    local directory=$(canonicalPathFor "$1")

    [[ -d "$directory" ]] || die "$directory does not exist; try again" 2
}


# *** main ***

set -e

assertMacOS

ls -Alrt "$MOUNT_POINT"

read -p "Which directory? " dirFlySight

assertFlySightDirExists "$dirFlySight"

workDirectory=$(canonicalPathFor "$dirFlySight")

printf "\nDisabling Spotlight scans on FlySight directory %s\n" "$workDirectory"
echo "This operation may take a while"
echo ""


# Via FlySight / Michael Cooper recommendation:
# https://apple.stackexchange.com/a/7135

mdutil -i off "$workDirectory" || die "mdutil failed, ABEND" 4

pushd "$workDirectory" > /dev/null
rm -rf .fseventsd .Spotlight-V* .Trashes ._.Trashes
mkdir .fseventsd
touch .fseventsd/no_log .metadata_never_index .Trashes
popd > /dev/null

printf "Spotlight disabled for $workDirectory\n\n"

exit 0

